apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: simple-webapp-nodeport
  namespace: simple-webapp
spec:
  ports:
  - name: port-1
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: simple-webapp
  type: NodePort
status:
  loadBalancer: {}
