apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: teamcity
  containers:
    - name: teamcity-container
      image: jetbrains/teamcity-server
      securityContext:
        runAsUser: 1000
      ports:
        - containerPort: 8111
          name: "teamcity-server"
      volumeMounts:
        - mountPath: "/data/teamcity_server/"
          name: storage
        - mountPath: "/opt/teamcity/"
          name: storage
