apiVersion: v1
kind: Pod
metadata:
  name: teamcity
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: teamcity
  containers:
    - name: teamcity-container
      image: jetbrains/teamcity-server
      ports:
        - containerPort: 8111
          name: "teamcity-server"
      volumeMounts:
        - mountPath: "/data/teamcity_server/datadir"
          name: storage
          subPath: data
        - mountPath: "/opt/teamcity/logs"
          name: storage
          subPath: logs
