apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: teamcity
  name: teamcity
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: teamcity
  type: NodePort
status:
  loadBalancer: {}
