apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: teamcity
  name: teamcity
  namespace: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teamcity
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: teamcity-datadir-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: teamcity-logs-pvc
      containers:
      - image: jetbrains/teamcity-server
        securityContext:
          runAsUser: 1000
        ports:
          - containerPort: 8111
            name: server
        volumeMounts:
          - mountPath: "/data/teamcity_server/datadir"
            name: datadir
          - mountPath: "/opt/teamcity/logs"
            name: logs
        name: teamcity
        resources: {}
status: {}
