apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: minio
  containers:
    - name: minio
      image: quay.io/minio/minio
      securityContext:
        runAsUser: 1000
      ports:
        - containerPort: 9000
          name: "ui"
        - containerPort: 9001
          name: "console"

      volumeMounts:
        - mountPath: "/data"
          name: storage
