apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-minio
  labels:
    type: local
spec:
  storageClassName: minio
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
