apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: simple-webapp
  namespace: simple-webapp
  labels:
    app: simple-webapp
spec:
  ports:
  - port: 8000
    name: web
    protocol: TCP
    targetPort: 8000
  - port: 8080
    name: metrics
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-webapp
status:
  loadBalancer: {}
